# Using mold under linux decreased total compilation time from 1m35s to 1m28s
# but increased a incremental time when changeing only main.rs from 18.6s to 2.1s
# Tested with Rust-Version 1.68.2

[build]
rustflags = ["--cfg", "tokio_unstable"]

# Running `cargo build --timings --target-dir {version}_target with different linters (04/2026, rust 1.95)
# - mold
#   - clean: 20.0, 20.0
#   - incremental: 1.42s, 1.39s
# - lld
#   - clean: 17.28, 18.05
#   - incremental: 1.36s, 1.34
#
# Infos
# - change in pilatus/Name.rs for incremental testing
# - `--target-dir` avoids `cargo clean` which might come with tasks like simultanous IDES language-server rebuilts.
# Conclusion: Mold is no longer worth it


#[target.x86_64-unknown-linux-gnu]
#rustflags = ["--cfg", "tokio_unstable", "-C", "link-arg=-fuse-ld=mold"]

